#/Library/Ruby/Gems/2.6.0/gems/minima-2.5.1/

title: The GlueX Experiment
#author: GitHub User
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  The goal of the GlueX experiment search for and study hybrid mesons.
  Hybrid mesons, and in particular exotic hybrid mesons, provide the ideal
  laboratory for testing QCD in the confinement regime since these mesons
  explicitly manifest the gluonic degrees of freedom. Photoproduction is
  expected to be particularly effective in producing exotic hybrids but
  there is little data on the photoproduction of light mesons. GlueX will
  use the coherent bremsstrahlung technique to produce a linearly polarized
  photon beam. A solenoid-based hermetic detector will be used to collected
  data on meson production and decays with statistics after the first year of
  running that will exceed the current photoproduction data in hand by several
  orders of magnitude. These data will also be used to study the spectrum of
  conventional mesons, including the poorly understood excited vector mesons
  and strangeonium. In order to reach the ideal photon energy of 9 GeV for
  this mapping of the exotic spectrum, 12 GeV electrons are required.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# generate social links in footer
twitter_username: Glue_X
facebook_username: GlueXperiment
instagram_username: gluexexperiment

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
