#/Library/Ruby/Gems/2.6.0/gems/minima-2.5.1/

title: The GlueX Experiment
#author: GitHub User
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  GlueX is a particle physics experiment located at Jefferson Lab in Newport News, VA.
  Its primary goal is to search for and study exotic hybrid mesons.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

header_pages:
- results.md
- collaboration.md
- bylaws.md
- management_plan.md

# generate social links in footer
twitter_username: Glue_X
facebook_username: GlueXperiment
instagram_username: gluexexperiment

# Build settings
theme: minima
#theme: minimal-mistakes-jekyll
#theme: minimal
#theme: hyde

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-gist
